name: Build

on: push

jobs:
    build:
        runs-on: windows-latest
        
        steps:
          - uses: actions/checkout@v2
          
          - name: Check codestyle
            run: git ls-files *.lua | xargs thirdparty/LuaFormatter/bin/win32/lua-format.exe -i --verbose && git diff --exit-code
            
          - name: Build application
            run: buiilder/CoronaBuilder.exe build --lua builder/build.android.lua
