name: Build

on: push

jobs:
    build:
        runs-on: windows-latest
        
        steps:
          - uses: actions/checkout@v2
          
          - name: Set up JDK 1.8
            uses: actions/setup-java@v1
            with:
                java-version: 1.8
            
          - name: Setup Android SDK
            uses: android-actions/setup-android@v2
            
          - name: Check codestyle
            run: git ls-files *.lua | xargs thirdparty/LuaFormatter/bin/win32/lua-format.exe -i --verbose && git diff --exit-code
            
          - uses: suisei-cn/actions-download-file@v1
            id: downloadfile
            name: Download the installator
            with:
                url: "https://github.com/coronalabs/corona/releases/download/3642/Solar2D-Windows-2021.3642.msi"
                target: public/
            
          - name: Install Corona
            run: msiexec.exe /i public\${{ steps.downloadfile.outputs.filename }} /passive
            
          - name: Build application
            run: make build
